<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>school</groupId>
  <artifactId>e-school</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>e-school Maven Webapp</name>
  <url>http://maven.apache.org</url>

  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.2.0</version> <!-- Синхронизируйте с spring-boot.version -->
    <relativePath/>
  </parent>

  <properties>
    <java.version>17</java.version>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
    <spring-boot.version>3.2.0</spring-boot.version>
    <postgresql.version>42.7.7</postgresql.version>
<!--    <flyway.version>10.0.0</flyway.version>-->
  </properties>

  <dependencies>
    <!-- Spring Boot -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
      <version>${spring-boot.version}</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>org.springframework.boot</groupId>-->
<!--      <artifactId>spring-boot-starter-security</artifactId>-->
<!--      <version>${spring-boot.version}</version>-->
<!--    </dependency>-->

    <!-- База данных -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>${postgresql.version}</version>
    </dependency>
<!--    <dependency>-->
<!--      <groupId>org.flywaydb</groupId>-->
<!--      <artifactId>flyway-maven-plugin</artifactId>-->
<!--      <version>${flyway.version}</version>-->
<!--    </dependency>-->

    <!-- Google Sheets API -->
<!--    <dependency>-->
<!--      <groupId>com.google.api-client</groupId>-->
<!--      <artifactId>google-api-client</artifactId>-->
<!--      <version>2.0.0</version>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>com.google.oauth-client</groupId>-->
<!--      <artifactId>google-oauth-client-jetty</artifactId>-->
<!--      <version>1.34.1</version>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>com.google.apis</groupId>-->
<!--      <artifactId>google-api-services-sheets</artifactId>-->
<!--      <version>v4-rev20220927-2.0.0</version>-->
<!--    </dependency>-->
<!--    <dependency>-->
<!--      <groupId>com.google.http-client</groupId>-->
<!--      <artifactId>google-http-client-jackson2</artifactId>-->
<!--      <version>1.47.0</version> &lt;!&ndash; Совместимая версия &ndash;&gt;-->
<!--    </dependency>-->

    <!-- Дополнительные утилиты -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <version>1.18.28</version>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains</groupId>
      <artifactId>annotations</artifactId>
      <version>24.0.0</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>3.2.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
<!--      <dependency>-->
<!--        <groupId>org.flywaydb</groupId>-->
<!--        <artifactId>flyway-core</artifactId>-->
<!--        <version>${flyway.version}</version>-->
<!--      </dependency>-->
    </dependencies>
  </dependencyManagement>
  <build>
    <finalName>e-school</finalName>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <version>${spring-boot.version}</version>
      </plugin>
<!--      <plugin>-->
<!--        <groupId>org.flywaydb</groupId>-->
<!--        <artifactId>flyway-maven-plugin</artifactId>-->
<!--        <version>${flyway.version}</version>-->
<!--        <configuration>-->
<!--          <url>jdbc:postgresql:file:./target/school</url>-->
<!--          <user>Niaverka Aliaksei</user>-->
<!--        </configuration>-->
<!--        <dependencies>-->
<!--          <dependency>-->
<!--            <groupId>com.h2database</groupId>-->
<!--            <artifactId>h2</artifactId>-->
<!--            <version>2.2.224</version>-->
<!--          </dependency>-->
<!--        </dependencies>-->
<!--      </plugin>-->
    </plugins>
  </build>
</project>
